yarnPath: .yarn/releases/yarn-4.3.1.cjs
nodeLinker: pnpm

npmScopes:
  fortawesome:
    npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  react-scripts@*:
    peerDependencies:
      sass: "*"
